name: Go_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: [started]
  schedule:
    - cron: 0 */8 * * *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Create dev.go
      run: |
           git clone https://github.com/cdle/sillyGirl.git
           mv dev.go.demo sillyGirl/dev.go

    - name: Git clone jd_cookie
      run:
        cd sillyGirl/develop && git clone https://github.com/ufuckee/jd_cookie.git

    - name: build
      run: |
           cd sillyGirl
           GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o sillyGirl_linux_arm64
           GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o sillyGirl_linux_amd64

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sillyGirl/sillyGirl_linux_amd64
        asset_name: sillyGirl_linux_amd64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sillyGirl/sillyGirl_linux_arm64
        asset_name: sillyGirl_linux_arm64
        tag: ${{ github.ref }}
        overwrite: true

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 10
